_aei_bienvenida:
    resource: "@ItsurAeiBundle/Controller/BienvenidaController.php"
    type:     annotation
    
_aei_evaluacion:
    resource: "@ItsurAeiBundle/Controller/EvaluacionController.php"
    type:     annotation
    
_aei_admin:
    resource: "@ItsurAeiBundle/Controller/AdministracionController.php"
    type:     annotation
    
_aei_admin_periodo:
    resource: "@ItsurAeiBundle/Controller/PeriodoController.php"
    type:     annotation
    
_aei_admin_aspirante:
    resource: "@ItsurAeiBundle/Controller/AspiranteController.php"
    type:     annotation

_aei_admin_estadisticos_previos:
    resource: "@ItsurAeiBundle/Controller/EstadisticosPreEvaluacionController.php"
    type:     annotation

_aei_admin_estadisticos_posteriores:
    resource: "@ItsurAeiBundle/Controller/EstadisticosPostEvaluacionController.php"
    type:     annotation

_aei_admin_manual:
    resource: "@ItsurAeiBundle/Controller/ManualController.php"
    type:     annotation

_aei_admin_area:
    resource: "@ItsurAeiBundle/Controller/AreaController.php"
    type:     annotation