<?php


namespace Itsur\AeiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvalubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{

    public function findByManual($manual)
    {
       $query = $this->getEntityManager()
        ->createQuery('
            SELECT a FROM ItsurAeiBundle:Area a
            JOIN a.manual as m
            WHERE
                m.id = :manual'
        )
        ->setParameter('manual', $manual);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
?>