<?php


namespace Itsur\AeiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository
{

    public function findByTema($temaid)
    {
       $query = $this->getEntityManager()
        ->createQuery('
            SELECT g FROM ItsurAeiBundle:Grupo g
            JOIN g.tema as t
            WHERE
                     pe.id = :periodo
              AND te.id = :temaid'
        )
        ->setParameter('periodo', $periodo)
        ->setParameter('temaid', $temaid);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
?>