<?php


namespace Itsur\AeiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvalubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends EntityRepository
{

    public function findByArea($claveManual, $nombreArea)
    {
       $query = $this->getEntityManager()
        ->createQuery('
            SELECT s FROM ItsurAeiBundle:Seccion s
            JOIN s.area as a
            JOIN a.manual m
            WHERE
                a.id = :area'
        )
        ->setParameter('area', $area);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
?>