<?php


namespace Itsur\AeiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoEvalubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaEvaluableRepository extends EntityRepository
{

    public function findByPeriodoAndFichaAndAreaAndSeccionAndOrder(
    $periodo, $ficha, $area, $seccion, $orden)
    {
       $query = $this->getEntityManager()
        ->createQuery('
            SELECT te FROM ItsurAeiBundle:TemaEvaluable te
            JOIN te.seccion as se
            JOIN se.area as ar
            JOIN ar.hoja as ho
            JOIN ho.aspirante as asp
            JOIN ho.periodo as pe
            WHERE
                     pe.id = :periodo
              AND asp.ficha = :ficha
              AND ar.orden = :areaorden
              AND se.orden = :seccionorden
              AND te.orden = :temaorden'
        )
        ->setParameter('periodo', $periodo)
        ->setParameter('ficha', $ficha)
        ->setParameter('areaorden', $area)
        ->setParameter('seccionorden', $seccion)
        ->setParameter('temaorden', $orden);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
?>